new FroalaEditor('.froalaeditor', {
	key: "1C%kZV[IX)_SL}UJHAEFZMUJOYGYQE[\\ZJ]RAe(+%$==",
	attribution: false,
	theme: 'gray',
    zIndex: 999,
	width: '100%',
	height: '250',
	language: 'ru',
	quickInsertButtons: "",
	imageAllowedTypes: ['jpeg', 'jpg', 'png', 'gif', 'webp'],
	imageUploadURL: '/control/dev/uploads',
	imageUploadMethod: 'POST',
	imageUploadParam: 'file',
	imageManagerLoadURL:"/control/dev/image_manager",
	imageManagerLoadMethod:"get",
	videoUploadURL: '/control/dev/upload_video',
	videoUploadParam: 'video_param',
	videoUploadMethod: 'POST',
	videoAllowedTypes: ['webm', 'ogg', 'mp4'],
	videoAllowedProviders: ['youtube', 'vimeo', 'rutube'],
	videoUpload: true,
	videoResponsive: true,
	imageManagerDeleteURL: "/control/dev/image_manager",
	imageManagerDeleteMethod: "POST",
	imageManagerDeleteParams: {delimage: '1'},
	toolbarButtonsXS: ['bold', 'italic', 'underline', 'strikeThrough', 'color','align','insertLink','insertVideo', 'insertImage',  'html'],
	toolbarButtonsSM: ['bold', 'italic', 'underline',  'strikeThrough', 'color','align',  'insertLink', 'insertVideo', 'insertImage',   'formatOL', 'formatUL', 'html'],
	toolbarButtonsMD: ['bold', 'italic', 'underline', 'strikeThrough','color', 'align', 'indent', 'outdent', 'subscript', 'superscript', 'insertTable', 'formatOL', 'formatUL', 'insertHR', 'undo', 'redo',  'clearFormatting', 'selectAll', 'fullscreen',  'insertLink', 'emoticons', 'insertVideo', 'insertImage', 'page_dropdown', 'html'],
	toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough','color', 'align', 'indent', 'outdent', 'subscript', 'superscript', 'insertTable', 'formatOL', 'formatUL', 'insertHR', 'undo', 'redo',  'clearFormatting', 'selectAll', 'fullscreen',  'insertLink', 'emoticons', 'insertVideo', 'insertImage', 'page_dropdown', 'html'],
})

new FroalaEditor('.froalalist', {
	key: "1C%kZV[IX)_SL}UJHAEFZMUJOYGYQE[\\ZJ]RAe(+%$==",
	attribution: false,
	theme: 'gray',
    zIndex: 999,
     enter: FroalaEditor.ENTER_BR,
	width: '100%',
	height: '250',
	language: 'ru',
	toolbarButtonsXS: [],
	toolbarButtonsSM:  [],
	toolbarButtonsMD:  [],
	toolbarButtons:  [],
})

new FroalaEditor('.froalapar', {
	key: "1C%kZV[IX)_SL}UJHAEFZMUJOYGYQE[\\ZJ]RAe(+%$==",
	attribution: false,
	theme: 'gray',
    zIndex: 999,
	width: '100%',
	height: '250',
	language: 'ru',
	toolbarButtonsXS: [],
	toolbarButtonsSM:  [],
	toolbarButtonsMD:  [],
	toolbarButtons:  [],
})

